name: Markdown Lint

on:
  push:
  pull_request:

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v23
